spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/authforge
    username: paapabentil
    password:

  jpa:
    hibernate:
      ddl-auto: none

  data:
    redis:
      host: localhost
      port: 6379

  flyway:
    enabled: true